apiVersion: v1
kind: Pod
metadata:
  labels:
    app: redis-pod
  name: redis-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: redis01
    image: {{ redis.image.name }}
    securityContext:
      allowPrivilegeEscalation: false
      privileged: false
      capabilities:
        add: []
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      seLinuxOptions: {}
    resources:
      requests:
        memory: {{ redis.resources.requests.memory }}
      limits:
        memory: {{ redis.resources.limits.memory }}
    ports:
    - containerPort: {{ redis.port.container }}
      hostPort: {{ redis.port.host }}
      hostIP: {{ redis.port.ip }}
      protocol: tcp
