# -*- coding: utf-8 -*-
# vim: ft=yaml

grafana:
  hostuser:
    name: vagrant
    group: vagrant
  pod:
    network:
      subnet: 10.77.1.0/24
      gateway: 10.77.1.1
      domain_name: grafananet
      bridge: cni-podman1
  grafana:
    image:
      name: docker.io/grafana/grafana:7.5.5
    port:
      http:
        container: 3000
        host: 3000
        ip: 127.0.0.1
    timezone: browser
    disable_sanitize_html: "false"
    db:
      type: mysql
      host: mysql-pod:3306
      name: grafanadb
      user: grafana
      password: abcde12345
    cache:
      type: redis
      addr: redis-pod:6379
      pool_size: 100
      db: 0
      ssl: "false"
    resources:
      requests:
        memory: 200Mi
      limits:
        memory: 200Mi
  mysql:
    image:
      name: docker.io/mysql/mysql-server:8.0
    port:
      container: 3306
      host: 3306
      ip: 127.0.0.1
    rootpassword: abcde12345
    dbname: grafanadb
    user:
      username: grafana
      password: abcde12345
    resources:
      requests:
        memory: 700Mi
      limits:
        memory: 700Mi
  redis:
    image:
      name: docker.io/redis:6.2-alpine
    port:
      container: 6379
      host: 6379
      ip: 127.0.0.1
    resources:
      requests:
        memory: 200Mi
      limits:
        memory: 200Mi
